source "$HOME/.sh/aliases.sh"
source "$HOME/.sh/brew.sh"
source "$HOME/.sh/functions.sh"
source "$HOME/.sh/env.sh"
source "$HOME/.sh/jump.sh"
source "$HOME/.sh/make.sh"
source "$HOME/.sh/go.sh"
source "$HOME/.sh/deno.sh"
source "$HOME/.sh/android.sh"

source "$HOME/.zsh/history.zsh"
source "$HOME/.zsh/prompt.zsh"
source "$HOME/.zsh/completion.zsh"
source "$HOME/.zsh/fzf.zsh"
