theme = "solarized_dark"

[editor]
line-number = "relative"
color-modes = true
cursorline = true
idle-timeout = 75
rulers = [80, 120]
auto-format = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
tabpad = "·"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
