[language-server.clangd]
command = "/opt/homebrew/opt/llvm/bin/clangd"

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = false

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--parser", "yaml"] }
auto-format = true

[[language]]
name = "java"
formatter = { command = "clang-format", args = ["--assume-filename=source.java"] }
auto-format = true

[[language]]
name = "c"
language-servers = ["clangd"]
auto-format = true

[[language]]
name = "cpp"
language-servers = ["clangd"]
auto-format = true

[[language]]
name = "objc"
scope = "source.objc"
roots = []
file-types = ["m"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["clangd"]
auto-format = true

[[grammar]]
name = "objc"
source = { git = "https://github.com/jiyee/tree-sitter-objc", rev = "afec0de5a32d5894070b67932d6ff09e4f7c5879" }

[[language]]
name = "objcpp"
scope = "source.objcpp"
roots = []
file-types = ["mm"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["clangd"]
auto-format = true

[[grammar]]
name = "objcpp"
source = { git = "https://github.com/panicinc/tree-sitter-objcpp", rev = "af4901aa56d459b33487c307f4951068a2365b1e" }
